### ISSUE TITLE
Notification delivered twice

### ISSUE THREAD

**Issue by otusweb** [bitrise-steplib/steps-slack-message#56]
Thanks for creating this step.
In my workflow, i added this step twice. Once at the beginning of the build to indicate that the build started and once at the end to indicate the build is done.

On pull request build, every notification (start and end) are being sent twice to our channel.

I'm not even sure where to start looking for what I did wrong.
Note that on a scheduled build, that has the same two notification steps, the notifications are only sent once

here is yml:
```
pull_request:
    steps:
    - comment-on-github-pull-request:
        inputs:
        - body: Check $BITRISE_BUILD_URL for details
        - personal_access_token: "$GITHUB_ACCESS_TOKEN"
    envs:
    - opts:
        is_expand: false
      FASTLANE_LANE: ios pullRequest
    - opts:
        is_expand: false
      FASTLANE_WORK_DIR: ios
    before_run:
    - Get_Code_Configure_Stack
    - code_quality
    - fastlane_build
fastlane_build:
    steps:
    - slack:
        inputs:
        - channel: "#dev-code-events"
        - text: 'A build just started on bitrise for branch $BITRISE_GIT_BRANCH '
        - channel_on_error: "#dev-code-events"
        - text_on_error: The build failed, please check why at $BITRISE_BUILD_URL
        - webhook_url: "$MONKEE_SLACK"
    - certificate-and-profile-installer: {}
    - fastlane:
        inputs:
        - lane: "$FASTLANE_LANE"
        - work_dir: "$FASTLANE_WORK_DIR"
    - deploy-to-bitrise-io:
        inputs:
        - deploy_path: "./ios/$IPA_NAME.ipa"
    - slack:
        inputs:
        - channel: "#dev-code-events"
        - text: Build successful!
        - channel_on_error: "#dev-code-events"
        - text_on_error: The build failed, please check why at $BITRISE_BUILD_URL
        - pretext: ''
        - webhook_url: "$MONKEE_SLACK"
    before_run: []
```

the workflow for the scheduled build:
```
iOS_daily:
    envs:
    - opts:
        is_expand: false
      FASTLANE_LANE: ios daily
    - opts:
        is_expand: false
      FASTLANE_WORK_DIR: ios
    before_run:
    - Get_Code_Configure_Stack
    - code_quality
    - fastlane_build
```
