### ISSUE TITLE
Bug when registering only the error channel

### ISSUE THREAD

**Issue by josinaldobarbosa** [bitrise-steplib/steps-slack-message#62]
When registering only the error channel and leave the success channel empty, the build success is sent to the error channel.

```
    - slack:
        inputs:
        - channel: ""
        - channel_on_error: "#my_channel_error"
        - webhook_url: "$my_url"
```

**Comment by bitce** [comment]
Hi @josinaldobarbosa! If you use a Webhook to access your Slack Workspace, this use case isn't possible because webhooks can only be created for specific channels. More on them here: https://api.slack.com/messaging/webhooks

**Comment by josinaldobarbosa** [comment]
I think I did not express myself well, in this case should not send to any channel since it was not placed in the same

**Comment by bitce** [comment]
Hi @josinaldobarbosa,

That is not accurate, due to what I've said a few weeks earlier, can you please check out the link?

Since your webhook was created for a specific channel, both options here:
```
  - channel: ""
  - channel_on_error: "#my_channel_error"
```

Are redundant. **A slack webhook is made specifically for one specific channel**. There is no way you can send a message to any other channel or user regardless of conditions.

These settings only apply when you use a bot token instead of a webhook.

**Comment by jazz-messenger** [comment]
Hi @bitce,

does this mean that I am not able to send a message to a different channel in the "build failed" case? I am asking this, because I do not see the option to define a 2nd webhook for this case anywhere.

Cheers, Jan.

**Comment by josinaldobarbosa** [comment]
@bitce my webhook is for any channel, that's not the problem, it seems to me that if you don't have the channel defined it is sending in the last channel used

**Comment by bitce** [comment]
Hi @jazz-messenger!

Yes, you are highly recommended to use a token instead of multiple webhooks.

@josinaldobarbosa 

Are you using a legacy Slack webhook created long ago? Otherwise what you are describing doesn't seem currently possible according to the Slack documentation I also linked above.

**Comment by koral--** [comment]
@josinaldobarbosa if you just want to sent slack message only for failed builds you add `run_if: .IsBuildFailed` to your bitrise.yml
https://devcenter.bitrise.io/jp/steps-and-workflows/disable-a-step-by-condition/

**Comment by josinaldobarbosa** [comment]
@bitce 
I tested another field and the behavior is similar, example
```
    - slack@3.1.3:
        inputs:
        - channel: "#teste-pessoal"
        - channel_on_error: "#teste-pessoal"
        - text: Success Message
        - webhook_url: "$SLACK_URL_ANDROID"
```
if the build fails the text is sent "Success Message", this should not be sent only on successful builds?
