### ISSUE TITLE
Action buttons behave differently on build success or failure

### ISSUE THREAD

**Issue by soucolline** [bitrise-steplib/steps-slack-message#73]
Hello, 

I've customised the action buttons on the step to add a link to the PR but it only appears when build succeed and not during a failure. I couldn't find a setting on the step to customise the buttons in case of failure so I guess it should be working the same whether it's a success or a failure ?

My yaml code : 
```
- slack@3:
        inputs:
        - channel: "#mobile-ci-status"
        - text: ":white_check_mark: Congratulation! Your build for :android: has succeeded! "
        - emoji: ''
        - text_on_error: ":x: Sorry... Your build for :android: has failed... "
        - emoji_on_error: ''
        - buttons: |
            View App|${BITRISE_APP_URL}
            View Build|${BITRISE_BUILD_URL}
            View PR|${GITHUB_PR_LINK}
        - webhook_url: "$slackWebhook"
```

The result on success is good with the three buttons : 
![Screenshot 2020-12-24 at 17 52 26](https://user-images.githubusercontent.com/8956641/103099960-ca286c80-4610-11eb-828a-9f48f68d3c9b.png)

But when it's an error the view PR disappears : 
![Screenshot 2020-12-24 at 17 53 00](https://user-images.githubusercontent.com/8956641/103099986-ddd3d300-4610-11eb-8657-b7d57ddc096a.png)

Is there something i'm missing during the setting of the step ?

Thank you in advance for your response and Merry Christmas 🙏
